Nils277/KerbalPlanetaryBaseSystems

GameData/PlanetaryBaseInc/ModSupport/Parts/LifeSupport/Container_Food_big.cfg
GameData/PlanetaryBaseInc/ModSupport/Parts/LifeSupport/Container_Food_small.cfg
GameData/PlanetaryBaseInc/ModSupport/Parts/LifeSupport/Container_Kerbalism_big.cfg
GameData/PlanetaryBaseInc/ModSupport/Parts/LifeSupport/Container_Kerbalism_small.cfg
GameData/PlanetaryBaseInc/ModSupport/Parts/LifeSupport/Container_Oxygen_big.cfg
GameData/PlanetaryBaseInc/ModSupport/Parts/LifeSupport/Container_Oxygen_small.cfg

Updates the amounts of food and o2 in storage units by 10x and 1,250x
respectively to match the changes made in kerbalism v0.9.9.5

Updates food and o2 amounts

---

GameData/PlanetaryBaseInc/ModSupport/Configs/LifeSupport/KPBS_MM_USI_LS.cfg
GameData/PlanetaryBaseInc/ModSupport/Parts/LifeSupport/Container_Greenhouse.cfg

These changes are from the discussion in the KPBS thread.

USI-LS updates

---

Translation/KSPedia es-es

Nils as promised Spanish translation for KSPedia

Create KSPedia es-es

---

Translation/en-us.cfg

For complete spanish description

Update spanish localization.cfg

---

Translation/ru.cfg

Fixed wrong case.
Fixed few untranslated strings.
Removed used comments. Added a couple more comments on comments.

Small update

---

Translation/ru.cfg

New parts translated.
Old comments removed.
For tags localization - poke someone else.  =^_^=

New parts translated

---

Translation/ru.cfg

Fancy russian quotes to match stock translation style.

Fancy quotes.

---

Translation/de-de.cfg

Corrected spelling mistakes & improved phrases

---

Translation/de-de.cfg
Translation/en-us.cfg

Continued translation corrections and enhancements to line 700

Localization: continued translation corrections and enhancements for de-de

---

Translation/KSPedia_de-de.cfg
Translation/de-de.cfg
Translation/en-us.cfg

Finished de-de translation Revision.

Finished de-de translation revision

---

readme.md

As I managed to create a KSP Forum account today, I changed my link from GitHub Profile to KSP Forums for consistency.

New link to KSP forum for @DasSkelett

---

FOR_RELEASE/GameData/PlanetaryBaseInc/Localization/en-us.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Configs/Kerbalism/KPBS_MM_Kerbalism_Habitation.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Configs/Kerbalism/Profiles/KPBS_MM_Kerbalism_Classic.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Configs/Kerbalism/Profiles/KPBS_MM_Kerbalism_Default.cfg

Kerbalism 1.6 will include some extra features (extra options for the ISRU) and balance changes (in the food area). This PR matches planetary parts with the kerbalism parts.

Kerbalism rebalance

---

FOR_RELEASE/GameData/PlanetaryBaseInc/Localization/en-us.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Configs/Kerbalism/Profiles/KPBS_MM_Kerbalism_Default.cfg

Some minor tweaks, I purposefully left out the "new" stuff (nitrogen excavation, ammonia from atmosphere, various things from oceans) because that was dropped in 5 minutes before 1.6.0 release and probably still unbalanced.

Minor fixes for Kerbalism

---

FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Configs/Kerbalism/Profiles/KPBS_MM_Kerbalism_Default.cfg

Several processes were missing the right pseudo-resources

define proper pseudo-resources (for kerbalism)

---

FOR_RELEASE/GameData/PlanetaryBaseInc/Localization/zh-cn.cfg

There is a lot of //TODO and it's been done years ago, clean up that. Also fixed some typos.
Question: Do I have to translate those tags, cause they are weird and I am still trying to figure out the compatibility, Can you tell me what does this thing do? Cause now they are totally messed up.

Translated update 1.6.4, did some cleanup

---

FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Parts/LifeSupport/Container_CO2_big.cfg

I noticed that MM now show its patch sequence and nicely complain about found errors.
And so it prompt for errors in one patch file.

Add missing colons

---

Translation/en-us.cfg

Please check if you find the grammatical changes acceptable. Pass 1 was intended to make the text sound like casual spoken English with very minor grammar corrections

Pass 1 - Updated Greenhouse items

---

FOR_RELEASE/GameData/PlanetaryBaseInc/Localization/pt-br.cfg

This is just to get rid of squares in the game UI.
Is there anyone working on finishing this translation?

Reencode Brazilian Portuguese localization file from ISO-8859-1 to UTF-8

---

Sources/PlanetarySurfaceStructures/SurfaceStructuresCategoryFilter.cs

Moved initialization of all Texture2D vars into method called by Awake()

---

Translation/zh-cn.cfg

Removed a dirty word and fixed typos

Fixed Chinese Traslation

---

FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Configs/Kerbalism/KPBS_MM_Kerbalism_Habitation.cfg

The parameters are approximated from other parts of similar dimensions.
closes #118

Add kerbalism habitat to modular corridors

---

FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Configs/LifeSupport/KPBS_MM_USI_LS.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Parts/DeepFreeze/Cryo5000Freezer/Cryo5000Freezer.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Parts/DeepFreeze/DF_TankGlykerol/tank_Glykerol.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Parts/LifeSupport/Container_CO2_big.cfg

This patch adds support for the "new" cryo freeze stuff which is in the pre-release of USI-LS. It's basically DeepFreeze with a new coat of paint and new backend code. So it's easiest to just reuse the existing DeepFreeze parts.
I also fixed a few typos in Container_CO2_big.cfg which threw MM for a loop.

add support for new USI-LS cryo freezing

---

FOR_RELEASE/GameData/PlanetaryBaseInc/Localization/de-de.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/Localization/en-us.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/Localization/es-es.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/Localization/it-it.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/Localization/ru.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Configs/Kerbalism/KPBS_MM_Kerbalism_Habitation.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Configs/Kerbalism/KPBS_MM_Kerbalism_Science.cfg
FOR_RELEASE/GameData/PlanetaryBaseInc/ModSupport/Configs/Kerbalism/Profiles/KPBS_MM_Kerbalism_Default.cfg

1) Fixed stale configs which causes NRE spam from Kerbalism.
2) Added missing Kerbalism ISRU option.
3) Added Kerbalism support for plant growth study experiment.
4) Added Kerbalism lab experiments to laboratory and central hub.
5) Removed duplicate laboratory module (now handled by Kerbalism).
6) Fixed habitat volume/surface numbers not being applied correctly. 
Please also see the forum thread for more context and details.

Kerbalism fix
